// =====================================================================
// Dream Country Visas — Complete Passport Power & Immigration Index
// Features ALL destination countries officially serviced by Dream Country Visas
// Zero AI imagery — uses official national passport scans & verified photography
// =====================================================================

export const PASSPORT_STATS_SUMMARY = {
  totalPrograms: 20,
  highestScore: 175, // Spain & Germany
  medianRank: 5,
  avgVisaFree: 135,
  cbiPrograms: 5,
  rbiPrograms: 9,
  prPrograms: 3,
  workPrograms: 3,
};

export const DC_PASSPORTS = [
  // ── CITIZENSHIP BY INVESTMENT (CBI) ──
  {
    id: 'malta',
    name: 'Malta',
    slug: 'malta',
    category: 'citizenship',
    categoryLabel: 'Citizenship by Investment (Direct CBI)',
    globalRank: 5,
    mobilityScore: 172,
    visaFree: 132,
    visaOnArrival: 40,
    visaRequired: 26,
    coverImage: '/real-passports/malta.jpg',
    realPhoto: '/images/country-malta.webp',
    flag: '🇲🇹',
    region: 'Europe',
    price: 'from €600,000',
    time: '12–36 months',
    tag: '⭐ Direct EU Passport',
    pathwayLink: '/citizenship/malta',
    summary: 'The sole direct European citizenship pathway. Grants full EU passport with unrestricted settlement rights across all 27 EU nations and visa-free travel to USA, UK, Canada & Japan.',
    legalData: [
      { label: 'Investment Route', value: 'NDSF Contribution (€600k/€750k) + Real Estate' },
      { label: 'Physical Stay Required', value: 'None after initial residency period' },
      { label: 'Family Inclusion', value: 'Spouse, Children under 29, Parents & Grandparents 55+' },
      { label: 'Tax Status', value: 'Non-dom tax benefits, no inheritance or wealth tax' },
      { label: 'Due Diligence Level', value: 'Tier-4 Enhanced EU/Interpol background check' },
      { label: 'Passport Validity', value: '10 Years biometric (Lifelong citizenship by descent)' },
    ],
  },
  {
    id: 'st-kitts-nevis',
    name: 'St. Kitts and Nevis',
    slug: 'st-kitts-nevis',
    category: 'citizenship',
    categoryLabel: 'Citizenship by Investment (CBI)',
    globalRank: 21,
    mobilityScore: 148,
    visaFree: 109,
    visaOnArrival: 39,
    visaRequired: 50,
    coverImage: '/passports/stkitts.jpg',
    realPhoto: '/images/country-stkitts.webp',
    flag: '🇰🇳',
    region: 'Caribbean',
    price: 'from $250,000',
    time: '4–6 months',
    tag: 'World’s Oldest CBI (Est. 1984)',
    pathwayLink: '/citizenship/st-kitts-nevis',
    summary: 'The platinum standard of global citizenship since 1984. Offers visa-free travel to the UK, Schengen Area, and Singapore with zero personal income, gift, or inheritance taxes.',
    legalData: [
      { label: 'Investment Route', value: 'SISC Contribution ($250k) or Approved Real Estate ($325k+)' },
      { label: 'Physical Stay Required', value: '0 Days (Zero physical residence required)' },
      { label: 'Family Inclusion', value: 'Spouse, Children under 26, Dependent parents 55+' },
      { label: 'Tax Status', value: '0% Personal income, capital gains & worldwide tax' },
      { label: 'Due Diligence Level', value: 'Strict CIU biometric & source of funds vetting' },
      { label: 'Passport Validity', value: '10 Years biometric, passed to future generations' },
    ],
  },
  {
    id: 'antigua-barbuda',
    name: 'Antigua and Barbuda',
    slug: 'antigua-barbuda',
    category: 'citizenship',
    categoryLabel: 'Citizenship by Investment (CBI)',
    globalRank: 24,
    mobilityScore: 144,
    visaFree: 106,
    visaOnArrival: 38,
    visaRequired: 54,
    coverImage: '/passports/antigua.jpg',
    realPhoto: '/images/country-antigua.webp',
    flag: '🇦🇬',
    region: 'Caribbean',
    price: 'from $230,000',
    time: '6–8 months',
    tag: 'Best Value for Large Families',
    pathwayLink: '/citizenship/antigua-barbuda',
    summary: 'Cost-effective CBI route for large families via the UWI Fund. Grants Commonwealth privileges, 140+ visa-free destinations, and tax-efficient offshore planning.',
    legalData: [
      { label: 'Investment Route', value: 'NDF Contribution ($230k) or UWI Fund ($260k family of 6)' },
      { label: 'Physical Stay Required', value: '5 Days total over the first 5 years' },
      { label: 'Family Inclusion', value: 'Spouse, Children under 29, Parents & Grandparents 55+' },
      { label: 'Tax Status', value: 'No tax on worldwide income, wealth or capital gains' },
      { label: 'Due Diligence Level', value: 'Complete CIU background & international law check' },
      { label: 'Passport Validity', value: '5 Years initial, renewable for 10-year validity' },
    ],
  },
  {
    id: 'vanuatu',
    name: 'Vanuatu',
    slug: 'vanuatu',
    category: 'citizenship',
    categoryLabel: 'Development Support Program (DSP)',
    globalRank: 48,
    mobilityScore: 98,
    visaFree: 62,
    visaOnArrival: 36,
    visaRequired: 100,
    coverImage: '/real-passports/vanuatu.jpg',
    realPhoto: '/images/country-vanuatu.webp',
    flag: '🇻🇺',
    region: 'Oceania',
    price: 'from $130,000',
    time: '2–3 months',
    tag: '⚡ Fastest Processing (60–90 Days)',
    pathwayLink: '/citizenship/vanuatu',
    summary: 'The world’s fastest citizenship by investment program. Fully remote process granting official citizenship and passport in just 60 to 90 days with zero physical presence required.',
    legalData: [
      { label: 'Investment Route', value: 'DSP Government Contribution (from $130,000)' },
      { label: 'Physical Stay Required', value: '0 Days (No travel or residency needed)' },
      { label: 'Family Inclusion', value: 'Spouse, Children under 25, Dependent parents' },
      { label: 'Tax Status', value: 'Zero income tax, zero corporate tax, tax-free haven' },
      { label: 'Due Diligence Level', value: 'Financial Intelligence Unit (FIU) pre-clearance in 48h' },
      { label: 'Passport Validity', value: '10 Years biometric passport' },
    ],
  },
  {
    id: 'nauru',
    name: 'Nauru',
    slug: 'nauru',
    category: 'citizenship',
    categoryLabel: 'Pacific Citizenship by Investment',
    globalRank: 62,
    mobilityScore: 86,
    visaFree: 48,
    visaOnArrival: 38,
    visaRequired: 112,
    coverImage: '/passports/nauru.jpg',
    realPhoto: '/images/country-nauru.webp',
    flag: '🇳🇷',
    region: 'Oceania',
    price: 'from $75,000',
    time: '3–6 months',
    tag: 'Most Confidential Pacific CBI',
    pathwayLink: '/citizenship/nauru',
    summary: 'Ultra-affordable and confidential second citizenship designed for high privacy, asset diversification, and international wealth protection at a lower entry cost than Caribbean programs.',
    legalData: [
      { label: 'Investment Route', value: 'Direct National Economic Contribution ($75k)' },
      { label: 'Physical Stay Required', value: '0 Days (Zero residency obligation)' },
      { label: 'Family Inclusion', value: 'Spouse, Children, Parents & Grandparents' },
      { label: 'Tax Status', value: 'Tax-friendly offshore financial framework' },
      { label: 'Due Diligence Level', value: 'Government intelligence verification' },
      { label: 'Passport Validity', value: '10 Years official passport' },
    ],
  },

  // ── RESIDENCY BY INVESTMENT & GOLDEN VISAS ──
  {
    id: 'spain',
    name: 'Spain',
    slug: 'spain',
    category: 'residency',
    categoryLabel: 'Residency by Investment (Golden Visa)',
    globalRank: 2,
    mobilityScore: 175,
    visaFree: 133,
    visaOnArrival: 42,
    visaRequired: 23,
    coverImage: '/real-passports/spain.jpg',
    realPhoto: '/images/res-spain.webp',
    flag: '🇪🇸',
    region: 'Europe',
    price: 'from €500,000',
    time: '3–6 months',
    tag: 'EU Golden Visa & Schengen Mobility',
    pathwayLink: '/residency/spain',
    summary: 'Direct Schengen residence permit with full freedom of travel across Europe. Direct pathway to Spanish permanent residency and European Union citizenship.',
    legalData: [
      { label: 'Investment Route', value: 'Real Estate (€500k) or Government Bonds (€2M)' },
      { label: 'Physical Stay Required', value: 'No minimum stay required to renew visa' },
      { label: 'Family Inclusion', value: 'Spouse, dependent children, dependent ascendants' },
      { label: 'Tax Status', value: 'Non-resident status available if under 183 days/yr' },
      { label: 'Work Rights', value: 'Full right to work and establish business in Spain' },
      { label: 'Path to Citizenship', value: 'Eligible for Spanish citizenship after 10 years (2 for LatAm)' },
    ],
  },
  {
    id: 'portugal',
    name: 'Portugal',
    slug: 'portugal',
    category: 'residency',
    categoryLabel: 'Residency by Investment (Golden Visa)',
    globalRank: 4,
    mobilityScore: 173,
    visaFree: 131,
    visaOnArrival: 42,
    visaRequired: 25,
    coverImage: '/real-passports/portugal.jpg',
    realPhoto: '/images/res-portugal.webp',
    flag: '🇵🇹',
    region: 'Europe',
    price: 'from €250,000',
    time: '18–24 months',
    tag: '7 Days Stay • Citizenship in 5 Years',
    pathwayLink: '/residency/portugal',
    summary: 'World-famous 7-day annual stay requirement. Grants complete Schengen mobility, European healthcare, and the fastest path to EU passport citizenship in 5 years.',
    legalData: [
      { label: 'Investment Route', value: 'Investment Funds (€500k) or Cultural Heritage (€250k)' },
      { label: 'Physical Stay Required', value: 'Only 7 days per year (14 days every 2 years)' },
      { label: 'Family Inclusion', value: 'Spouse, Children under 26 in school, Parents 65+' },
      { label: 'Tax Status', value: 'Exemption from tax on foreign source dividends' },
      { label: 'Work Rights', value: 'Full employment and business registration rights' },
      { label: 'Path to Citizenship', value: 'Apply for Portuguese EU passport after 5 years' },
    ],
  },
  {
    id: 'greece',
    name: 'Greece',
    slug: 'greece',
    category: 'residency',
    categoryLabel: 'Golden Visa & Real Estate',
    globalRank: 5,
    mobilityScore: 172,
    visaFree: 130,
    visaOnArrival: 42,
    visaRequired: 26,
    coverImage: '/real-passports/greece.png',
    realPhoto: '/images/re-greece.webp',
    flag: '🇬🇷',
    region: 'Europe',
    price: 'from €250,000',
    time: '4–6 months',
    tag: '5-Year Renewable European Residence',
    pathwayLink: '/realestate/greece',
    summary: 'Instant 5-year renewable European residency for 3 generations via freehold property ownership. Unrestricted travel across 29 Schengen member states.',
    legalData: [
      { label: 'Investment Route', value: 'Real Estate from €250k (conversion) or €400k/€800k prime' },
      { label: 'Physical Stay Required', value: '0 Days (Zero minimum stay to maintain permit)' },
      { label: 'Family Inclusion', value: 'Spouse, Children under 21, Parents of both spouses' },
      { label: 'Tax Status', value: '7% Flat tax regime available for foreign pensioners' },
      { label: 'Rental Income', value: 'Full rights to rent out property for euro returns' },
      { label: 'Permit Duration', value: '5 Years, renewable indefinitely with property ownership' },
    ],
  },
  {
    id: 'italy',
    name: 'Italy',
    slug: 'italy',
    category: 'residency',
    categoryLabel: 'Investor Visa & Dolce Vita Residency',
    globalRank: 3,
    mobilityScore: 174,
    visaFree: 132,
    visaOnArrival: 42,
    visaRequired: 24,
    coverImage: '/real-passports/italy.jpg',
    realPhoto: '/images/res-italy.webp',
    flag: '🇮🇹',
    region: 'Europe',
    price: 'from €250,000',
    time: '3–6 months',
    tag: 'Italian Investor Visa & Flat Tax',
    pathwayLink: '/residency/italy',
    summary: 'Direct investor visa into Europe’s 3rd largest economy. Pair with Italy’s famous €100,000/year flat tax regime on all global foreign income for exceptional wealth protection.',
    legalData: [
      { label: 'Investment Route', value: 'Innovative Startup (€250k) or Italian Company (€500k)' },
      { label: 'Physical Stay Required', value: 'Zero strict stay requirement' },
      { label: 'Family Inclusion', value: 'Spouse, minor children, dependent adult children' },
      { label: 'Tax Status', value: 'Optional €100k lump-sum flat tax on worldwide income' },
      { label: 'Work Rights', value: 'Work, manage enterprise, and live anywhere in Italy' },
      { label: 'Path to Citizenship', value: 'Italian EU passport eligibility after 10 years' },
    ],
  },
  {
    id: 'cyprus',
    name: 'Cyprus',
    slug: 'cyprus',
    category: 'residency',
    categoryLabel: 'Permanent Residency by Investment',
    globalRank: 7,
    mobilityScore: 170,
    visaFree: 128,
    visaOnArrival: 42,
    visaRequired: 28,
    coverImage: '/real-passports/cyprus.jpg',
    realPhoto: '/images/res-cyprus.webp',
    flag: '🇨🇾',
    region: 'Europe',
    price: 'from €300,000',
    time: '3–4 months',
    tag: 'Fast-Track PR in 90 Days',
    pathwayLink: '/residency/cyprus',
    summary: 'Permanent residency granted in 3–4 months with no language exams, 12.5% corporate tax rate, and lifetime validity for the applicant, spouse, and dependent children.',
    legalData: [
      { label: 'Investment Route', value: 'New Residential Real Estate (€300,000 + VAT)' },
      { label: 'Physical Stay Required', value: 'Visit Cyprus once every 2 years' },
      { label: 'Family Inclusion', value: 'Spouse and unmarried dependent children up to 25' },
      { label: 'Tax Status', value: '12.5% Corporate tax, 0% tax on dividends for non-doms' },
      { label: 'Permit Duration', value: 'Permanent for life (never expires)' },
      { label: 'Path to Citizenship', value: 'Naturalisation eligible after 5 years of physical stay' },
    ],
  },
  {
    id: 'latvia',
    name: 'Latvia',
    slug: 'latvia',
    category: 'residency',
    categoryLabel: 'Golden Visa & Real Estate',
    globalRank: 9,
    mobilityScore: 169,
    visaFree: 126,
    visaOnArrival: 43,
    visaRequired: 29,
    coverImage: '/real-passports/latvia.jpg',
    realPhoto: '/images/res-latvia.webp',
    flag: '🇱🇻',
    region: 'Europe',
    price: 'from €250,000',
    time: '2–3 months',
    tag: 'Lowest European Entry Threshold',
    pathwayLink: '/residency/latvia',
    summary: 'Fast-track 5-year European residence permit with unrestricted Schengen travel, low living costs, and access to the European banking and business market.',
    legalData: [
      { label: 'Investment Route', value: 'Real Estate (€250,000) or Subordinated Bank Capital' },
      { label: 'Physical Stay Required', value: 'Visit once a year to renew ID card' },
      { label: 'Family Inclusion', value: 'Spouse and minor children under 18' },
      { label: 'Tax Status', value: 'Competitive corporate tax with 0% reinvested profit tax' },
      { label: 'Schengen Access', value: 'Full borderless travel across 29 European nations' },
      { label: 'Permit Duration', value: '5-Year renewable residence card' },
    ],
  },
  {
    id: 'new-zealand',
    name: 'New Zealand',
    slug: 'new-zealand',
    category: 'residency',
    categoryLabel: 'Active Investor Plus Residency',
    globalRank: 6,
    mobilityScore: 171,
    visaFree: 129,
    visaOnArrival: 42,
    visaRequired: 27,
    coverImage: '/passports/new-zealand.jpg',
    realPhoto: '/images/res-nz.webp',
    flag: '🇳🇿',
    region: 'Oceania',
    price: 'from NZD 3M+',
    time: '6–12 months',
    tag: 'Top Quality of Life & Bilateral Rights',
    pathwayLink: '/residency/new-zealand',
    summary: 'Premier lifestyle destination with unmatched global safety and bilateral living rights in Australia. Direct residency for investors funding innovative enterprises.',
    legalData: [
      { label: 'Investment Route', value: 'Active Investor Plus (NZD 5M direct / NZD 15M weighted)' },
      { label: 'Physical Stay Required', value: '117 days across 3 years (flexible stay)' },
      { label: 'Family Inclusion', value: 'Spouse and dependent children aged 24 and under' },
      { label: 'Australia Access', value: 'Direct right to live, study and work in Australia' },
      { label: 'Tax Status', value: 'Transitional tax resident exemption for first 4 years' },
      { label: 'Passport Validity', value: 'Rank #6 globally, bilateral Australasia freedom' },
    ],
  },
  {
    id: 'uae',
    name: 'United Arab Emirates',
    slug: 'uae',
    category: 'residency',
    categoryLabel: '10-Year Golden Visa & Real Estate',
    globalRank: 11,
    mobilityScore: 164,
    visaFree: 122,
    visaOnArrival: 42,
    visaRequired: 34,
    coverImage: '/real-passports/uae.jpg',
    realPhoto: '/images/re-dubai.webp',
    flag: '🇦🇪',
    region: 'Middle East',
    price: 'from AED 2M',
    time: '2–4 weeks',
    tag: '10-Year Renewable Golden Visa',
    pathwayLink: '/realestate/dubai',
    summary: '0% personal income tax, 100% foreign business ownership, world-class luxury infrastructure, and 10-year renewable Golden Visa through property or executive status.',
    legalData: [
      { label: 'Investment Route', value: 'Property purchase (AED 2M+) or Executive / Entrepreneur' },
      { label: 'Physical Stay Required', value: 'No stay requirement (remain valid even if outside UAE > 6 mo)' },
      { label: 'Family Inclusion', value: 'Spouse, children of any age, domestic staff' },
      { label: 'Tax Status', value: '0% Personal income tax, 0% capital gains, 0% inheritance tax' },
      { label: 'Business Ownership', value: '100% foreign ownership of mainland & freezone companies' },
      { label: 'Permit Duration', value: '10-Year renewable self-sponsored residence visa' },
    ],
  },

  // ── PERMANENT RESIDENCY (PR) ──
  {
    id: 'australia',
    name: 'Australia',
    slug: 'australia',
    category: 'pr',
    categoryLabel: 'Permanent Residency & National Innovation',
    globalRank: 7,
    mobilityScore: 171,
    visaFree: 128,
    visaOnArrival: 43,
    visaRequired: 27,
    coverImage: '/real-passports/australia.jpg',
    realPhoto: '/images/res-australia.webp',
    flag: '🇦🇺',
    region: 'Oceania',
    price: 'from AUD 250,000',
    time: '8–14 months',
    tag: 'Universal Medicare & Direct PR',
    pathwayLink: '/pr/australia',
    summary: 'Direct Permanent Residency pathway granting free universal Medicare healthcare, subsidized education, and Australian passport eligibility for the entire family.',
    legalData: [
      { label: 'Immigration Route', value: 'National Innovation Visa / Skilled PR (Subclass 189/190)' },
      { label: 'Physical Stay Required', value: 'Live in Australia to qualify for citizenship' },
      { label: 'Family Inclusion', value: 'Spouse, dependent children under 23' },
      { label: 'Healthcare & Welfare', value: 'Full Medicare healthcare and social security benefits' },
      { label: 'Representation', value: 'Handled by registered MARA agent (MARN 0100178)' },
      { label: 'Citizenship Path', value: 'Australian citizenship and passport after 4 years' },
    ],
  },
  {
    id: 'canada',
    name: 'Canada',
    slug: 'canada',
    category: 'pr',
    categoryLabel: 'Permanent Residency & Startup Visa',
    globalRank: 8,
    mobilityScore: 170,
    visaFree: 127,
    visaOnArrival: 43,
    visaRequired: 28,
    coverImage: '/real-passports/canada.jpg',
    realPhoto: '/images/res-canada.webp',
    flag: '🇨🇦',
    region: 'Americas',
    price: 'from CAD 75,000',
    time: '12–16 months',
    tag: 'Direct PR • Universal Healthcare',
    pathwayLink: '/pr/canada',
    summary: 'North America’s leading immigration gateway. Direct Permanent Residency for entrepreneurs, angel-funded startups, and skilled professionals with citizenship in 3 years.',
    legalData: [
      { label: 'Immigration Route', value: 'Startup Visa (SUV) or Express Entry / PNP Streams' },
      { label: 'Physical Stay Required', value: '730 days (2 years) within any 5-year period' },
      { label: 'Family Inclusion', value: 'Spouse and dependent children under 22' },
      { label: 'Healthcare & Education', value: 'Universal healthcare & free public primary/secondary schools' },
      { label: 'Work Rights', value: 'Unrestricted open work and business privileges anywhere in Canada' },
      { label: 'Path to Citizenship', value: 'Canadian passport eligibility after 3 years (1,095 days)' },
    ],
  },

  // ── WORK, EMPLOYMENT & SKILLED MIGRATION ──
  {
    id: 'germany',
    name: 'Germany',
    slug: 'germany',
    category: 'work',
    categoryLabel: 'Opportunity Card & Skilled Employment',
    globalRank: 2,
    mobilityScore: 175,
    visaFree: 133,
    visaOnArrival: 42,
    visaRequired: 23,
    coverImage: '/real-passports/germany.jpg',
    realPhoto: '/images/country-germany.webp',
    flag: '🇩🇪',
    region: 'Europe',
    price: 'from €100–150 gov fee',
    time: '6–8 weeks',
    tag: 'Chancenkarte Points-Based Job Visa',
    pathwayLink: '/services/work-visas',
    summary: 'Germany’s official Opportunity Card (Chancenkarte). Points-based job search visa allowing 1 year to secure employment in Europe’s largest industrial powerhouse without a prior job offer.',
    legalData: [
      { label: 'Visa Category', value: 'Chancenkarte (Opportunity Card) / EU Blue Card' },
      { label: 'Job Offer Requirement', value: 'No job offer required to apply' },
      { label: 'Work Allowance', value: 'Up to 20 hours/week part-time work permitted during job search' },
      { label: 'Family Rights', value: 'Family reunification permitted upon securing full employment' },
      { label: 'Conversion', value: 'Seamless conversion to EU Blue Card / permanent residence' },
      { label: 'Fast-Track PR', value: 'Permanent residence after 21–27 months with B1 German' },
    ],
  },
  {
    id: 'sweden',
    name: 'Sweden',
    slug: 'sweden',
    category: 'work',
    categoryLabel: 'Work Permit & Skilled Employment',
    globalRank: 3,
    mobilityScore: 174,
    visaFree: 132,
    visaOnArrival: 42,
    visaRequired: 24,
    coverImage: '/real-passports/sweden.jpg',
    realPhoto: '/images/country-sweden.webp',
    flag: '🇸🇪',
    region: 'Europe',
    price: 'from SEK 2,000 fee',
    time: '2–4 months',
    tag: 'Work Permit & PR in 4 Years',
    pathwayLink: '/services/work-visas',
    summary: 'Nordic employment visa with world-class work-life balance, high wages, comprehensive social safety nets, and a direct path to Swedish permanent residency and EU passport.',
    legalData: [
      { label: 'Visa Category', value: 'Swedish Employer-Sponsored Work Permit' },
      { label: 'Wage Standards', value: 'Must meet Swedish collective bargaining salary minimums' },
      { label: 'Family Inclusion', value: 'Spouse receives full open work permit, children get free school' },
      { label: 'Social Benefits', value: 'Universal Nordic healthcare, paid parental leave & childcare' },
      { label: 'Permanent Residence', value: 'Direct eligibility for Swedish PR after 4 years of work' },
      { label: 'Path to Citizenship', value: 'Swedish EU passport after 5 years total residence' },
    ],
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    slug: 'uk',
    category: 'work',
    categoryLabel: 'Skilled Worker & Global Business Mobility',
    globalRank: 4,
    mobilityScore: 173,
    visaFree: 131,
    visaOnArrival: 42,
    visaRequired: 25,
    coverImage: '/real-passports/uk.svg',
    realPhoto: '/landing-img/hero-london.png',
    flag: '🇬🇧',
    region: 'Europe',
    price: 'from £625 gov fee',
    time: '3–8 weeks',
    tag: 'Skilled Worker & ILR Pathway',
    pathwayLink: '/services/work-visas',
    summary: 'Access the world’s leading financial and legal capital. Direct pathways for sponsored professionals, international business expansions, and indefinite leave to remain (ILR).',
    legalData: [
      { label: 'Visa Category', value: 'Skilled Worker / Senior Specialist Worker / Innovator' },
      { label: 'Sponsorship', value: 'Requires Certificate of Sponsorship (CoS) from licensed employer' },
      { label: 'Family Inclusion', value: 'Spouse receives dependent work rights, children access NHS' },
      { label: 'Healthcare Access', value: 'Full National Health Service (NHS) coverage via IHS' },
      { label: 'Indefinite Leave (ILR)', value: 'Eligible for UK Permanent Residence (ILR) after 5 years' },
      { label: 'British Passport', value: 'British citizenship eligibility 12 months after receiving ILR' },
    ],
  },
  {
    id: 'usa',
    name: 'United States',
    slug: 'usa',
    category: 'work',
    categoryLabel: 'EB-5 Investor & Executive L-1 Visas',
    globalRank: 8,
    mobilityScore: 170,
    visaFree: 127,
    visaOnArrival: 43,
    visaRequired: 28,
    coverImage: '/real-passports/usa.jpg',
    realPhoto: '/landing-img/hero-dubai.png',
    flag: '🇺🇸',
    region: 'Americas',
    price: 'from $800,000 (EB-5)',
    time: '6–18 months',
    tag: 'US Green Card Pathway',
    pathwayLink: '/services/investor-visas',
    summary: 'The gold standard in global business opportunities. EB-5 Immigrant Investor Green Cards and L-1 intra-company transfer visas providing permanent settlement in the United States.',
    legalData: [
      { label: 'Immigration Route', value: 'EB-5 Immigrant Investor / L-1A Multinational Executive' },
      { label: 'Physical Stay Required', value: 'Maintain US Green Card permanent residence rules' },
      { label: 'Family Inclusion', value: 'Spouse and unmarried children under 21 included' },
      { label: 'Work & Study Rights', value: 'Live, work, and attend universities anywhere in the USA' },
      { label: 'Green Card Status', value: 'Direct pathway to Permanent Resident status' },
      { label: 'US Citizenship', value: 'Eligible for US Passport after 5 years of Green Card status' },
    ],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    slug: 'singapore',
    category: 'work',
    categoryLabel: 'Company Setup & Employment Pass (EP)',
    globalRank: 1,
    mobilityScore: 176,
    visaFree: 134,
    visaOnArrival: 42,
    visaRequired: 22,
    coverImage: '/real-passports/singapore.jpg',
    realPhoto: '/landing-img/Glob.webp',
    flag: '🇸🇬',
    region: 'Asia',
    price: 'from $5,000 setup',
    time: '3–6 weeks',
    tag: 'Asia’s #1 Financial Hub',
    pathwayLink: '/services/company-setup',
    summary: 'World’s most powerful passport with access to 176 nations. Incorporate your global enterprise in Singapore with 17% corporate tax rate and obtain an executive Employment Pass.',
    legalData: [
      { label: 'Immigration Route', value: 'Employment Pass (EP) via Singapore Company Setup' },
      { label: 'COMPASS Points', value: 'Points-based framework evaluated on salary and qualifications' },
      { label: 'Family Inclusion', value: 'Dépandant’s Pass (DP) for spouse and unmarried children' },
      { label: 'Tax Status', value: 'Tiered 0–22% personal tax, 0% capital gains tax, single tier' },
      { label: 'Permanent Residence', value: 'Eligible to apply for Singapore PR after 2 years of EP status' },
      { label: 'Global Ranking', value: 'Consistently ranked #1 or #2 strongest passport worldwide' },
    ],
  },
];
